(() => {
"use strict";
const MONTHS=[["2026-09","Septembre 2026"],["2026-10","Octobre 2026"],["2026-11","Novembre 2026"],["2026-12","Décembre 2026"],["2027-01","Janvier 2027"],["2027-02","Février 2027"],["2027-03","Mars 2027"],["2027-04","Avril 2027"],["2027-05","Mai 2027"],["2027-06","Juin 2027"],["2027-07","Juillet 2027"],["2027-08","Août 2027"]];
const ENVS=[
{name:"Alimentation",icon:"🍎",b:900,a:900},{name:"Essence",icon:"⛽",b:200,a:200},{name:"Restaurant",icon:"🍽️",b:120,a:120},{name:"Argent de poche",icon:"💶",b:60,a:60},{name:"Abonnements",icon:"📺",b:95,a:66},{name:"Vêtements / chaussures",icon:"👕",b:180,a:180},{name:"Bricolage / rénovation",icon:"🔨",b:250,a:250},{name:"Sports / activités",icon:"🏒",b:600,a:600},{name:"Cadeaux",icon:"🎁",b:250,a:250},{name:"Vacances",icon:"✈️",b:45,a:74},{name:"Coiffeur",icon:"✂️",b:50,a:50},{name:"Repas extérieurs Guillaume",icon:"🥪",b:150,a:150},{name:"Épargne",icon:"💰",b:300,a:300}
];
const PEOPLE=["Famille","Laura","Guillaume","Manon","Sacha","Gabin","Maison","Vacances 1","Vacances 2"];
const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(Number(n)||0);
let sb,session,month=localStorage.getItem("bf_v2_month")||"2026-09",expenses=[],budgets=[],incomes=[],channel=null,editing=null,timer=null;
const def=(e,m)=>(m==="2026-09"||m==="2026-10")?e.b:e.a;
const budget=(name,m=month)=>{const r=budgets.find(x=>x.mois===m&&x.enveloppe===name);return r?Number(r.montant):def(ENVS.find(e=>e.name===name),m)};
const income=(m=month)=>{const r=incomes.find(x=>x.mois===m);return r?Number(r.montant):3200};
const mexp=(m=month)=>expenses.filter(x=>String(x.date_depense).slice(0,7)===m);const spent=(n,m=month)=>mexp(m).filter(x=>x.enveloppe===n).reduce((s,x)=>s+Number(x.montant),0);
function toast(t){clearTimeout(timer);$("toast").textContent=t;$("toast").classList.remove("hidden");timer=setTimeout(()=>$("toast").classList.add("hidden"),2400)}
function view(v){$("loadingScreen").classList.add("hidden");$("loginView").classList.toggle("hidden",v!=="login");$("appView").classList.toggle("hidden",v!=="app")}
function initControls(){$("monthSelect").innerHTML=MONTHS.map(m=>`<option value="${m[0]}">${m[1]}</option>`).join("");$("monthSelect").value=month;$("expenseCategory").innerHTML=ENVS.map(e=>`<option value="${e.name}">${e.icon} ${e.name}</option>`).join("");$("expensePerson").innerHTML=PEOPLE.map(p=>`<option>${p}</option>`).join("");$("expenseDate").value=new Date().toISOString().slice(0,10)}
async function init(){if(!window.supabase||!window.BUDGET_CONFIG){$("loadingScreen").innerHTML="<strong>Chargement impossible</strong>";return}sb=window.supabase.createClient(BUDGET_CONFIG.supabaseUrl,BUDGET_CONFIG.supabasePublishableKey);initControls();events();const r=await sb.auth.getSession();session=r.data.session;sb.auth.onAuthStateChange((_e,s)=>{session=s;s?start():view("login")});session?await start():view("login")}
async function login(){const email=$("loginEmail").value.trim(),password=$("loginPassword").value;if(!email||!password){$("loginMessage").textContent="Renseignez l’adresse e-mail et le mot de passe.";return}$("loginBtn").disabled=true;const {error}=await sb.auth.signInWithPassword({email,password});$("loginBtn").disabled=false;if(error)$("loginMessage").textContent="Connexion impossible : vérifiez les identifiants."}
async function start(){view("app");$("accountEmail").textContent=session.user.email||"";await defaults();await load();realtime()}
async function defaults(){const uid=session.user.id;let r=await sb.from("budgets").select("id").limit(1);if(r.error)throw r.error;if(!r.data.length){const rows=[];for(const m of MONTHS)for(const e of ENVS)rows.push({user_id:uid,mois:m[0],enveloppe:e.name,montant:def(e,m[0])});r=await sb.from("budgets").insert(rows);if(r.error)throw r.error}r=await sb.from("revenus").select("id").limit(1);if(r.error)throw r.error;if(!r.data.length){r=await sb.from("revenus").insert(MONTHS.map(m=>({user_id:uid,mois:m[0],montant:3200})));if(r.error)throw r.error}}
async function load(){$("syncStatus").textContent="Synchronisation…";const [d,b,i]=await Promise.all([sb.from("depenses").select("*").order("date_depense",{ascending:false}).order("created_at",{ascending:false}),sb.from("budgets").select("*"),sb.from("revenus").select("*")]);if(d.error||b.error||i.error)throw(d.error||b.error||i.error);expenses=d.data||[];budgets=b.data||[];incomes=i.data||[];render();$("syncStatus").textContent="Synchronisé"}
function render(){const label=MONTHS.find(m=>m[0]===month)?.[1]||month;$("headerMonth").textContent=label;$("monthSelect").value=month;const total=mexp().reduce((s,x)=>s+Number(x.montant),0);$("incomeValue").textContent=euro(income());$("spentValue").textContent=euro(total);$("availableValue").textContent=euro(income()-total);$("availableValue").classList.toggle("negative",income()-total<0);renderEnvs();preview();renderList()}
function renderEnvs(){$("envelopeGrid").innerHTML=ENVS.map(e=>{const b=budget(e.name),u=spent(e.name),l=b-u,p=b?Math.min(100,u/b*100):0,c=u>b?"over":u>b*.85?"warn":"";return `<button class="envelope" data-env="${esc(e.name)}"><div class="envelope-head"><div><div class="envelope-icon">${e.icon}</div><h3>${esc(e.name)}</h3></div><div class="envelope-budget">${euro(b)}</div></div><div class="progress"><div class="progress-bar ${c}" style="width:${p}%"></div></div><div class="envelope-used">${euro(u)} dépensés</div><div class="envelope-left ${l<0?"negative":""}">${euro(l)} restants</div></button>`}).join("");document.querySelectorAll("[data-env]").forEach(b=>b.onclick=()=>openBudget(b.dataset.env))}
function preview(){const n=$("expenseCategory").value||ENVS[0].name,a=Number($("expenseAmount").value)||0,b=budget(n),u=spent(n)+a,l=b-u,p=b?Math.min(100,u/b*100):0;$("previewCategory").textContent=n;$("previewRemaining").textContent=euro(l);$("previewRemaining").classList.toggle("negative",l<0);$("previewUsed").textContent=`${euro(u)} après dépense`;$("previewBudget").textContent=`Budget ${euro(b)}`;$("previewProgress").style.width=p+"%";$("previewProgress").className=`progress-bar ${u>b?"over":u>b*.85?"warn":""}`}
function renderList(){const q=$("expenseSearch").value.trim().toLowerCase();let rows=[...expenses];if(q)rows=rows.filter(x=>[x.libelle,x.enveloppe,x.personne,x.ajoute_par].filter(Boolean).join(" ").toLowerCase().includes(q));$("expenseCount").textContent=`${rows.length} dépense${rows.length>1?"s":""}`;$("expenseList").innerHTML=rows.length?rows.map(x=>`<article class="expense-row"><div><strong>${esc(x.libelle||x.enveloppe)}</strong><div class="expense-meta">${new Date(x.date_depense+"T12:00:00").toLocaleDateString("fr-FR")} · ${esc(x.enveloppe)} · ${esc(x.personne||"Famille")}${x.ajoute_par?` · par ${esc(x.ajoute_par)}`:""}</div></div><div class="expense-side"><div class="expense-amount">${euro(x.montant)}</div><button class="delete-btn" data-del="${x.id}">Supprimer</button></div></article>`).join(""):"<div class='empty-state'>Aucune dépense enregistrée.</div>";document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>del(b.dataset.del))}
async function saveExpense(){const date=$("expenseDate").value,amount=Number($("expenseAmount").value);if(!date||!amount||amount<=0){$("expenseMessage").textContent="Indiquez une date et un montant supérieur à zéro.";return}const {error}=await sb.from("depenses").insert({user_id:session.user.id,date_depense:date,montant:amount,enveloppe:$("expenseCategory").value,personne:$("expensePerson").value,libelle:$("expenseLabel").value.trim()||null,ajoute_par:$("expenseAuthor").value});if(error){console.error(error);$("expenseMessage").textContent="Enregistrement impossible.";return}$("expenseAmount").value="";$("expenseLabel").value="";month=date.slice(0,7);localStorage.setItem("bf_v2_month",month);await load();screen("dashboardScreen");toast("Dépense synchronisée.")}
async function del(id){if(!confirm("Supprimer cette dépense pour tous les appareils ?"))return;const {error}=await sb.from("depenses").delete().eq("id",id);if(error)return toast("Suppression impossible.");await load();toast("Dépense supprimée.")}
function openBudget(n){editing=n;$("budgetModalName").value=n;$("budgetModalAmount").value=budget(n);$("budgetModalMonth").textContent=MONTHS.find(m=>m[0]===month)?.[1]||month;modal("budgetModal")}
async function saveBudget(){const amount=Number($("budgetModalAmount").value);if(!editing||amount<0)return;const {error}=await sb.from("budgets").upsert({user_id:session.user.id,mois:month,enveloppe:editing,montant:amount,updated_at:new Date().toISOString()},{onConflict:"user_id,mois,enveloppe"});if(error){console.error(error);return toast("Modification impossible.")}closeModal();await load();toast("Enveloppe mise à jour.")}
function openIncome(){$("incomeModalAmount").value=income();$("incomeModalMonth").textContent=MONTHS.find(m=>m[0]===month)?.[1]||month;modal("incomeModal")}
async function saveIncome(){const amount=Number($("incomeModalAmount").value);if(amount<0)return;const {error}=await sb.from("revenus").upsert({user_id:session.user.id,mois:month,montant:amount,updated_at:new Date().toISOString()},{onConflict:"user_id,mois"});if(error){console.error(error);return toast("Modification impossible.")}closeModal();await load();toast("Revenu mis à jour.")}
function realtime(){if(channel)sb.removeChannel(channel);channel=sb.channel("budget-family-"+session.user.id).on("postgres_changes",{event:"*",schema:"public",table:"depenses"},()=>setTimeout(()=>load().catch(console.error),150)).on("postgres_changes",{event:"*",schema:"public",table:"budgets"},()=>setTimeout(()=>load().catch(console.error),150)).on("postgres_changes",{event:"*",schema:"public",table:"revenus"},()=>setTimeout(()=>load().catch(console.error),150)).subscribe(s=>{if(s==="SUBSCRIBED")$("syncStatus").textContent="Temps réel actif"})}
function modal(id){$("modalBackdrop").classList.remove("hidden");$("budgetModal").classList.toggle("hidden",id!=="budgetModal");$("incomeModal").classList.toggle("hidden",id!=="incomeModal")}
function closeModal(){$("modalBackdrop").classList.add("hidden");$("budgetModal").classList.add("hidden");$("incomeModal").classList.add("hidden");editing=null}
function screen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===id));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.screen===id));if(id==="expenseScreen")preview()}
function exportCsv(){const rows=[["Date","Montant","Enveloppe","Personne","Libellé","Ajouté par"],...expenses.map(x=>[x.date_depense,Number(x.montant).toFixed(2).replace(".",","),x.enveloppe,x.personne||"",x.libelle||"",x.ajoute_par||""])];const txt=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n"),blob=new Blob(["\ufeff"+txt],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="Budget_familial_depenses_V2.0.0.csv";document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(url);a.remove()},1000)}
function events(){$("loginBtn").onclick=login;$("loginPassword").onkeydown=e=>{if(e.key==="Enter")login()};$("monthSelect").onchange=e=>{month=e.target.value;localStorage.setItem("bf_v2_month",month);render()};$("syncBtn").onclick=()=>load().catch(console.error);$("refreshBtn").onclick=()=>load().then(()=>toast("Données actualisées."));$("incomeBtn").onclick=openIncome;$("saveIncomeBtn").onclick=saveIncome;$("saveBudgetBtn").onclick=saveBudget;$("saveExpenseBtn").onclick=saveExpense;$("expenseCategory").onchange=preview;$("expenseAmount").oninput=preview;$("expenseSearch").oninput=renderList;document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>{$("expenseAmount").value=(Number($("expenseAmount").value)||0)+Number(b.dataset.quick);preview()});document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>screen(b.dataset.screen));document.querySelectorAll("[data-close-modal]").forEach(b=>b.onclick=closeModal);$("modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")closeModal()};$("logoutBtn").onclick=()=>sb.auth.signOut();$("exportBtn").onclick=exportCsv}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
init().catch(e=>{console.error(e);$("loadingScreen").innerHTML="<strong>Erreur de démarrage</strong><span>Vérifiez Supabase et la connexion.</span>"});
})();